### ISSUE TITLE
Website URL is down

### ISSUE THREAD

**Issue by berezovskyi** [eea/sparql-client#12]
<h2>Site Error</h2> <p>An error was encountered while publishing this resource. </p> <p><strong>Resource not found</strong></p> Sorry, the requested resource does not exist.<p>Check the URL and try again.</p><p><b>Resource:</b> http://www.eionet.europa.eu/software/sparql-client</p> <hr noshade="noshade"/> <p>Troubleshooting Suggestions</p> <ul> <li>The URL may be incorrect.</li> <li>The parameters passed to this resource may be incorrect.</li> <li>A resource that this resource relies on may be encountering an error.</li> </ul> <p>For more detailed information about the error, please refer to the error log. </p> <p>If the error persists please contact the site maintainer. Thank you for your patience. </p>

**Comment by alecghica** [comment]
@berezovskyi how you get to this URL (http://www.eionet.europa.eu/software/sparql-client)? This URL doesn't exist so that's why you get the "Resource not found" error.

**Comment by berezovskyi** [comment]
The URL is shown on both

* https://pypi.python.org/pypi/sparql-client/2.7
* https://github.com/eea/sparql-client#sparql-http-client-library

With the text *"Visit http://www.eionet.europa.eu/software/sparql-client/ for documentation and examples."*

**Comment by alecghica** [comment]
@berezovskyi the issue was tracked in our internal ticketing system and it will be addressed shortly. Once the issue will be fixed the documentation will be available under the [EEA & Eionet documentation hub](https://eea.github.io/docs/).

For now you can find the information you are looking for here:

- http://web.archive.org/web/20131011101917/http://www.eionet.europa.eu:80/software/sparql-client/
- https://github.com/eea/sparql-client/tree/master/docs
