### ISSUE TITLE
Update PYPI version

### ISSUE THREAD

**Issue by fnielsen** [eea/sparql-client#9]
The present PYPI version (1.9) is somewhat old and may result in `sparql.SparqlException` that apparently is impossible to work around, as per #7. It may be a good idea to update the PYPI version.

Note also the problem with the `__version__` variable, cf. #8.

**Comment by alecghica** [comment]
@fnielsen the issue was tracked under https://taskman.eionet.europa.eu/issues/74151 and the latest version of sparql-client will be available on PyPi in max 2 weeks from now.

If you need the latest egg right now you can get it from EEA's Python Egg repository: http://eggrepo.apps.eea.europa.eu/simple/

**Comment by alecghica** [comment]
Released latest version on PyPi.

**Comment by fnielsen** [comment]
I can confirm that version 2.2 on PYPI works for me now. Thanks!
